
version: 2

sources:
  - name: pressure_monitoring
    description: "Currently contains datasets of corporate communications that are not primary sources for benchmarking (e.g., earnings call transcripts)."
    database: sri-benchmarking-databases
    schema: pressure_monitoring
    
    tables:

      - name: earnings_call_transcript_metadata
        description: "Source data for information about each earnings call transcript, like call date and company. Pulled on a weekly basis from the defeatbeta API (Yahoo Finance data)."
        columns:
          - name: transcript_id
            description: '{{ doc("earnings_call_transcript_id") }}'
            tests:
              - unique
              - not_null
          - name: symbol
            description: '{{ doc("symbol_or_ticker") }}'
            tests:
            - not_null
          - name: report_date
            description: "Date on which the call occured"
            tests:
            - not_null
          - name: fiscal_year
            description: '{{ doc("fiscal_year") }}'
          - name: fiscal_quarter
            description: '{{ doc("fiscal_quarter") }}'
            config:
              tags: "earnings_calls"
          
      - name: earnings_call_transcript_content
        description: "Source data for content from each earnings call transcript, like speakers and transcript segments. Pulled on a weekly basis from the defeatbeta API (Yahoo Finance data)."
        columns:
            - name: transcript_id
              description: '{{ doc("earnings_call_transcript_id") }}'
              tests:
                - unique
                - not_null
            - name: paragraph_number
              description: '{{ doc("earnings_call_paragraph_number") }}'
              tests:
                  - not_null
            - name: speaker
              description: '{{ doc("earnings_call_speaker") }}'
              tests:
                  - not_null
            - name: content
              description: '{{ doc("earnings_call_content") }}'
              tests:
                  - not_null
        config:
          tags: "earnings_calls"



  - name: social_media_activity_archive
    database: sri-benchmarking-databases
    schema: social_media_activity_archive
    tables:
      - name: external_benchmarking_corporate_reference
      - name: external_analyst_ced_subs
      - name: external_ceo_benchmarking_reference
      - name: external_issue_term_reference
      - name: external_engagement_term_reference
      - name: instagram_posts_copy # Raw Instagram data
      - name: linkedin_posts_copy # Raw LinkedIn data
      - name: x_posts # Raw X data
      - name: ceo_linkedin_posts # Raw CEO LinkedIn data
      - name: ceo_twitter_posts # Raw CEO X data
      - name: tagged_records # Finalized corporate engagement data
      - name: benchmarking_issue_tagged # This is present only for the first run


  - name: non_socials_engagement_data
    description: "This database contains inputs to our benchmarking pipeline that are not directly scraped from social media platforms. While social media content may still be present, it is returned by the SERP scraper managed by Digital or from other 'third-party' collection methods."
    database: sri-benchmarking-databases
    schema: non_socials_engagement_data
    tables:
      - name: engagement_data_outputs_raw # What tests do I need for this one?
        description: "This table contains the raw outputs of the Corporate Engagement Scraper maintained by the National Journal Digital team. Each record is a distinct instance of a potential corporate engagement, accompanied by metadata and an LLM-generated confidence score for whether or not it is actually an engagement."


  - name: zignal_gold
    database: sri-monitoring-pipeline
    schema: zignal_gold
    tables:
      - name: story
        config:
          tags: "pressure_monitoring"
      - name: story_cluster_mapping
        config:
          tags: "pressure_monitoring"