
version: 2

sources:
  - name: pressure_monitoring
    database: sri-benchmarking-databases
    schema: pressure_monitoring
    tables:
      - name: earnings_call_transcript_metadata
      - name: earnings_call_transcript_content
      
  - name: social_media_activity_archive
    database: sri-benchmarking-databases
    schema: social_media_activity_archive
    tables:
      - name: external_benchmarking_corporate_reference
      - name: external_analyst_ced_subs
      - name: external_ceo_benchmarking_reference
      - name: external_issue_term_reference